baseURL = "https://lookgoodkillgood.com/"
languageCode = "en-us"
title = "LGK.GG"
theme = "ananke"

sectionPagesMenu = "main"

[params]
  featured_image = "images/fortnite_wallpaper.jpeg"
  custom_css = ["css/custom.css"]
  favicon = ""
  site_logo = ""
  description = "Looking this good isn't as easy as it looks."
  facebook = ""
  twitter = "https://twitter.com/lgkg_gaming"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCWH7iHzgDFMZIklMo7NhCSg"
  github = "https://github.com/lookgoodkillgood"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
